
version: '3.3'
services:
  postgres:
    env_file:
      - .env
    image: 'postgres:alpine'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  mysql:
    env_file:
      - .env
    image: mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DB}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      ports: '${MYSQL_PORT}=${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - './mydata:/var/lib/mysql'
  mariadb:
    env_file:
      - .env
    image: mariadb
    environment:
      MYSQL_DATABASE: '${MYSQL_DB}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      ports: '${MYSQL_PORT}=${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - './madata:/var/lib/mysql'

