version: '3.3'

services:
  mariadb:
    env_file:
      - .env
    image: mariadb 
    environment:
      MYSQL_DATABASE: ${MYSQL_DB} 
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      ports: ${MYSQL_PORT}=${MYSQL_PORT}
        # <Port exposed> : < MySQL Port running inside container>
    expose:
      # Opens port 3306 on the container
      - ${MYSQL_PORT}
      # Where our data will be persisted
    volumes:
      - ./madata:/var/lib/mysql
