users:
  admin:
    disabled: false
    displayname: "Playground Admin"
    # PASTE THE HASH FROM THE COMMAND ABOVE HERE:
    password: "$argon2id$v=19$m=65536,t=3,p=4$YOUR_HASH_HERE"
    email: admin@localhost
    groups:
      - admins